# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

before_install:
  - |
      # Install `ShellCheck`.
      #
      # ShellCheck is required for testing and
      # is included with Travis's Ubuntu builds,
      # so it only needs to be installed for the
      # macOS ones.
      if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew install shellcheck
      fi

branches:
  only:
    - master
    - stage

install:
  - bash -c "$(wget -qO - https://raw.githubusercontent.com/musq/dotfiles-system/master/src/os/setup.sh) -y"
  - source /etc/profile
  - ./src/os/setup.sh -y

matrix:
  include:

    - os: linux
      dist: trusty

    - os: linux
      dist: bionic

notifications:
  email:
    on_failure: always
    on_success: never

script:
  - ./tests/shellcheck.sh
